[pylint]
disable = "all"

[flake8]
ignore = "F,E,W,C"

[translations.python-specific.pylint]
value = "--enable=unidiomatic-typecheck,misplaced-format-function,use-enumerate,consider-iterating-dictionary,consider-using-dict-items,consider-using-f-string,inconsistent-return-statements,consider-swap-variables,consider-using-join,consider-using-set-comprehension,unnecessary-comprehension,use-a-generator,use-list-literal,use-dict-literal,consider-using-in,"

[translations.enhancement.pylint]
value = "--enable=no-self-use,superfluous-parens,consider-using-min-builtin,consider-using-max-builtin,consider-using-with,unspecified-encoding,loop-shadows-control-variable,no-repeated-op,forbidden-top-level-code,simplifiable-if-nested,simplifiable-if-seq,simplifiable-if-return-conj,simplifiable-if-assignment-conj,simplifiable-if-expr-conj,"

[translations.complexity.pylint]
value = "--enable=too-many-arguments,too-many-branches,too-many-statements,too-many-return-statements,too-many-nested-blocks,too-many-locals,too-many-boolean-expressions,"

groups = ["python-specific", "enhancement", "complexity"]
