name: Test, Publish and Deploy new tagged version

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  publish-package:
    needs: test
    uses: ./.github/workflows/python-publish.yaml
    secrets: inherit

  deploy:
    needs: publish-package
    uses: ./.github/workflows/redeploy-web.yaml
    secrets: inherit
      
  publish-docker:
    needs: publish-package
    uses: ./.github/workflows/docker-build-and-publish.yaml
    secrets: inherit
    with:
      docker-labels: edulint/edulint-cli:latest,edulint/edulint-cli:${{ github.ref }}

      
