name: Run tests


on:
  push:
  workflow_call:

jobs:
  pytest:
    # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [3.8, 3.9, "3.10", 3.11]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: '${{ secrets.PAT_PRIVATE_TESTS }}'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements.dev.txt ]; then pip install -r requirements.dev.txt; fi
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi

      - name: Install Edulint
        run: pip install --upgrade .

      - name: Test with pytest
        run: pytest --junit-xml pytest.xml tests/

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Unit Test Results (Python ${{ matrix.version }})
          path: pytest.xml

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: pytest
    runs-on: ubuntu-latest
    if: success() || failure()
    permissions:
      checks: write
      pull-requests: write  # only needed unless run with comment_mode: off
      contents: read  # only needed for private repository
      issues: read  # only needed for private repository

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.4.2
        with:
          files: "artifacts/**/pytest.xml"
